# Use OpenJDK as base image
FROM openjdk:17

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=Mysql2025 \
    MYSQL_DATABASE=mydb \
    MYSQL_USER=root1 \
    MYSQL_PASSWORD=mypass

# Install MySQL
RUN apt-get update && \
    apt-get install -y gnupg lsb-release wget && \
    wget https://dev.mysql.com/get/mysql-apt-config_0.8.29-1_all.deb && \
    DEBIAN_FRONTEND=noninteractive dpkg -i mysql-apt-config_0.8.29-1_all.deb && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server && \
    rm -rf /var/lib/apt/lists/*

# Copy the Java app JAR
COPY target/demo-app.jar /usr/app/
WORKDIR /usr/app/

# Expose Java app and MySQL ports
EXPOSE 8080 3306

# Copy custom entrypoint to start both services
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
